export const TRANSLATE_MAP = {
    "Clothing": "Clothing",
    "T-SHIRT": "T-Shirt",
    "SWEATSHIRT": "Sweatshirt",
    "Sweatshirt": "Sweatshirt",
    "Hoodie": "Hoodie",
    "HOODIE": "Hoodie",
    "Zipper Hoodie": "Zipper Hoodie",
    "ZIPPERHOODIE": "Zipper Hoodie",
    "SweatPants": "Sweatpants",
    "SWEATPANTS": "Sweatpants",
    "SHORTS": "Shorts",
    "Size and color": "Size and Color",
    "Pressure": "Pressure",
    "Farve & Størrelse": "Color & Size",
    "Color & Size": "Color & Size",
    "Design": "Design",
    "Color": "Color",
    "Size": "Size",
    "Back Design Library": "Back Design Library",
    "Loading countries...": "Loading countries...",
    "No designs for this country": "No designs for this country",
    "Loading...": "Loading...",
    "Next — Design": "Next — Design",
    "Back": "Back",
    "T-shirt": "T-Shirt",
    "Red": "Red",
    "Orange": "Orange",
    "Lime": "Lime",
    "Kit": "Kit",
    "Light blue": "Light Blue",
    "Turquoise": "Turquoise",
    "Navy": "Navy",
    "Black": "Black",
    "White (black print)": "White (black print)",
    "S": "S",
    "M": "M",
    "L": "L",
    "XL": "XL",
    "2XL": "2XL",
    "3XL": "3XL",
    "Size guide": "Size Guide",
    "Samlet pris": "Total Price",
    "400 DKK": "400 DKK",
    "Servicegebyr på 59,00 kr. inkl.": "Service fee of 59.00 kr. included",
    "Godkend og betal": "Approve and Pay",
    "Chest Area": "Chest Area",
    "Right Chest:": "Right Chest:",
    "Left Chest:": "Left Chest:",
    "Free text": "Free Text",
    "Enter text": "Enter text",
    "Predefined flag": "Predefined Flag",
    "Select flag": "Select Flag",
    "Select": "Select",
    "Sleeves": "Sleeves",
    "Right Sleeve:": "Right Sleeve:",
    "Left Sleeve:": "Left Sleeve:",
    "Pressure Options": "Pressure Options",
    "Right Chest": "Right Chest",
    "Left:": "Left:",
    "Right:": "Right:",
    "Select a Flag": "Select a Flag",
    "Short": "Short",
    "Add to cart": "Add to Cart",
    "Total Price": "Total Price",
    "Design Back": "Design Back",
    "Log Out": "Log Out",
    "StudentLife": "StudentLife",
    "Cloth Configurator": "Cloth Configurator",
    "Selected": "Selected",
    "LIVE PREVIEW": "LIVE PREVIEW",
    "White": "White",
    "Natural": "Natural",
    "Heather Grey": "Heather Grey",
    "Light Pink": "Light Pink",
    "Olive Green": "Olive Green",
    "Blue": "Blue",
    "Purple": "Purple",
    "Service fee of 59.00 kr. included": "Service fee of 59.00 kr. included",
    "Select Type": "Select Type",
    "Flag": "Flag",
    "Logo": "Logo",
    "Students": "Students",
    "Individual Configuration": "Individual Configuration",
    "Approve and Pay": "Approve and Pay",
    "Add Students": "Add Students",
    "Individual": "Individual",
    "Batch (Multiple)": "Batch (Multiple)",
    "Student Name": "Student Name",
    "Enter full name": "Enter full name",
    "Student Names (max 10)": "Student Names (max 10)",
    "+ Add another student": "+ Add another student",
    "Save & Continue": "Save & Continue",
    "Student 1": "Student 1",
    "Student 2": "Student 2",
    "Student 3": "Student 3",
    "Student 4": "Student 4",
    "Student 5": "Student 5",
    "Student 6": "Student 6",
    "Student 7": "Student 7",
    "Student 8": "Student 8",
    "Student 9": "Student 9",
    "Student 10": "Student 10",
    "Currently Editing:": "Currently Editing:",
    "Leg Area": "Leg Area",
    "Right Leg:": "Right Leg:",
    "Left Leg:": "Left Leg:",
    "right Chest:": "Right Chest:",
    "right Sleeve:": "Right Sleeve:",
    "Back Design:": "Back Design:",
    "Finish": "Finish",
    "Global Back Design": "Global Back Design",
    "Design uploaded here will be applied to ALL students.": "Design uploaded here will be applied to ALL students.",
    "Login": "Login",
    "Sign in to manage your dashboard": "Sign in to manage your dashboard",
    "Log in": "Log in",
    "© 2024 ClothConfig. All rights reserved.": "© 2024 ClothConfig. All rights reserved.",

    // Countries
    "Denmark": "Denmark",
    "United States": "United States",
    "United Kingdom": "United Kingdom",
    "Germany": "Germany",
    "France": "France",
    "Spain": "Spain",
    "Italy": "Italy",
    "Netherlands": "Netherlands",
    "Sweden": "Sweden",
    "Norway": "Norway",
    "Finland": "Finland",
    "Poland": "Poland",
    "Japan": "Japan",
    "South Korea": "South Korea",
    "China": "China",
    "India": "India",
    "Brazil": "Brazil",
    "Canada": "Canada",
    "Australia": "Australia",
    "Mexico": "Mexico",

    "View More Countries": "View More Countries",
    "Show Less": "Show Less",
    "more": "more",
    "Text": "Text",
    "Number of flags:": "Number of flags:",
    "Text color:": "Text color:",
    "Select logo": "Select Logo",
    "Select a Logo": "Select a Logo",
    "Choose a Flag": "Choose a Flag",
    "Pick a symbol for your design": "Pick a symbol for your design",
    "Represent your country": "Represent your country",
    "No logos found": "No logos found",
    "Logos assigned to your class will appear here.": "Logos assigned to your class will appear here.",
    "Choose an asset to customize your placement": "Choose an asset to customize your placement",
    "Flag 1 (50% size)": "Flag 1 (50% size)",
    "Flag 2 (50% size)": "Flag 2 (50% size)",

    "Upload own design": "Upload own design",
    "Add classmates names": "Add classmates names",
    "Your class needs to be signed up before you can add your own design.": "Your class needs to be signed up before you can add your own design.",
    "To upload your own design, you need to send a request first. Once your request is approved, you will be able to upload your design.": "To upload your own design, you need to send a request first. Once your request is approved, you will be able to upload your design.",
    "Send request": "Send request",
    "Copy Design?": "Copy Design?",
    "Haan, Copy Karo": "Yes, Copy",
    "Nahi, Alag Rakho": "No, Keep Separate",

    // Save Design Modal
    "Select Garments to Save": "Select Garments to Save",
    "Select karein jo order mein jaane chahiye": "Select items to include in your order",
    "Select items to include in your order": "Select items to include in your order",
    "Save Karein": "Save",
    "Cancel": "Cancel",
    "Kam az kam ek garment select karein.": "Please select at least one garment.",
    "Pehle koi garment configure karein.": "Please configure at least one garment first.",
};
