export const TRANSLATE_MAP = {
    // ── NAVIGATION / GARMENT TYPES ──
    "Clothing": "Tøj",
    "T-SHIRT": "T-Shirt",
    "SWEATSHIRT": "Crewneck",
    "Sweatshirt": "Crewneck",
    "SweatShirt": "Crewneck",
    "Hoodie": "Hoodie",
    "HOODIE": "Hoodie",
    "Zipper Hoodie": "Lynlås Hoodie",
    "ZIPPERHOODIE": "Lynlås Hoodie",
    "SweatPants": "Sweatpants",
    "SWEATPANTS": "Sweatpants",
    "SHORTS": "Shorts",
    "T-shirt": "T-Shirt",

    // ── TABS ──
    "Color & Size": "Farve og Størrelse",
    "Farve & Størrelse": "Farve og Størrelse",
    "Size and color": "Farve og Størrelse",
    "Design": "Design",
    "Pressure": "Tryk",

    // ── COLOR SECTION ──
    "Color": "Farve",
    "Red": "Rød",
    "Orange": "Orange",
    "Lime": "Lime",
    "Kit": "Kit",
    "Light blue": "Lyseblå",
    "Turquoise": "Turkis",
    "Navy": "Navy",
    "Black": "Sort",
    "White": "Hvid",
    "White (black print)": "Hvid (sort tryk)",
    "Natural": "Lys beige",
    "Heather Grey": "Lysegrå",
    "Light Pink": "Lyserød",
    "Olive Green": "Olivengrøn",
    "Blue": "Blå",
    "Purple": "Lilla",

    // ── SIZE SECTION ──
    "Size": "Størrelse",
    "S": "S",
    "M": "M",
    "L": "L",
    "XL": "XL",
    "2XL": "2XL",
    "3XL": "3XL",
    "Size guide": "Størrelsesguide",

    // ── BACK DESIGN LIBRARY ──
    "Back Design Library": "Bibliotek med rygtryk",
    "Garment Color": "Tøjfarve",
    "Light Garment": "Lyst tøj",
    "Black print": "Mørkt print",
    "Dark Garment": "Mørkt tøj",
    "White print": "Lyst print",
    "Loading countries...": "Indlæser Lande",
    "Select a country above": "Vælg et land",
    "No designs for this country": "Der findes ingen designs til dette land",
    "Show Less": "Vis færre",
    "View More Countries": "Vis flere lande",
    "more": "flere",
    "Upload own design": "Upload eget design",
    "Add classmates names": "Tilføj klassekammeraters navne",

    // ── CHEST AREA ──
    "Chest Area": "Brysttryk",
    "Right Chest:": "Højre bryst",
    "Left Chest:": "Venstre bryst",
    "Bottom Chest:": "Nederst på brystet (kun hoodie)",
    "Right Chest": "Højre bryst",
    "right Chest:": "Højre bryst:",
    "Left:": "Venstre:",
    "Right:": "Højre:",

    // ── SLEEVE AREA ──
    "Sleeves": "Ærmer",
    "Right Sleeve:": "Højre ærme",
    "Left Sleeve:": "Venstre ærme",
    "right Sleeve:": "Højre ærme:",

    // ── LEG AREA ──
    "Leg Area": "Benområde",
    "Right Leg:": "Højre ben",
    "Left Leg:": "Venstre ben",

    // ── TYPE TABS ──
    "Text": "Tekst",
    "Flag": "Flag",
    "Logo": "Logo",
    "Select Type": "Vælg type",

    // ── TEXT MODE ──
    "Enter text": "Indsæt text",
    "Free text": "Fri tekst",
    "Free Text": "Fri tekst",
    "Text color:": "Tekst Farve",
    "Number of flags:": "Antal af flag",

    // ── FLAG MODE ──
    "Select flag": "Vælg Flag",
    "Select a Flag": "Vælg et flag",
    "Choose a Flag": "Udvælg et flag",
    "Pick a symbol for your design": "Vælg et symbol til dit design",
    "Represent your country": "Repræsentér dit land",
    "Flag 1 (50% size)": "Flag 1 (reduceret størrelse)",
    "Flag 2 (50% size)": "Flag 2 (reduceret størrelse)",

    // ── LOGO MODE ──
    "Select logo": "Vælg Logo",
    "Select a Logo": "Vælg et logo",
    "Choose an asset to customize your placement": "Vælg et element, som du vil placere på dit design",
    "Logos assigned to your class will appear here.": "Logoer, der er tilknyttet din klasse, vises her.",
    "No logos found": "Ingen logoer fundet",

    // ── BUTTONS / ACTIONS ──
    "Select": "Vælg",
    "Back": "Tilbage",
    "Finish": "Færdig",
    "Cancel": "Annuller",
    "Save": "Gem",
    "Save & Continue": "Gem og fortsæt",
    "Save Design": "Gem design",
    "Send request": "Send forespørgsel",
    "Send Inquiry": "Send forespørgsel",
    "Add to cart": "Tilføj til kurv",
    "Add to Cart": "Tilføj til kurv",
    "Approve and Pay": "Godkend og betal",
    "Godkend og betal": "Godkend og betal",
    "Next — Design": "Næste Design",
    "Live Preview": "Livevisning",
    "LIVE PREVIEW": "LIVEVISNING",
    "History": "Historik",
    "Undo": "Fortryd",
    "Reset Order": "Nulstil ordre",
    "Close": "Luk",
    "Restore": "Gendan",

    // ── SAVE GARMENT MODAL ──
    "Select Garments to Save": "Vælg tøj, der skal gemmes",
    "Select karein jo order mein jaane chahiye": "Vælg de produkter, du vil inkludere i din ordre",
    "Select items to include in your order": "Vælg de produkter, du vil inkludere i din ordre",
    "Save Karein": "Gem",
    "Kam az kam ek garment select karein.": "Vælg mindst ét produkt.",
    "Pehle koi garment configure karein.": "Tilpas mindst ét produkt først.",
    "Please select at least one garment.": "Vælg mindst ét produkt.",
    "Please configure at least one garment first.": "Tilpas mindst ét produkt først.",

    // ── ORDER MODAL ──
    "Order Overview": "Ordreoversigt",
    "Delivery Information": "Leveringsoplysninger",
    "Order Confirmation": "Ordrebekræftelse",
    "Thank You": "Tak for din bestilling",
    "Select Items to Purchase": "Vælg produkter, du vil købe",
    "Click the checkbox on each garment card to select/deselect items for your order.": "Sæt flueben ved de produkter, du ønsker at bestille.",
    "Price will update automatically based on your selection.": "Prisen opdateres automatisk ud fra dine valg.",
    "Custom Configuration": "Personligt design",
    "Selected": "Valgt",
    "Not Selected": "Ikke valgt",
    "No Items Selected": "Ingen produkter valgt",
    "Please select at least one garment to continue with your order.": "Vælg mindst ét stykke tøj for at fortsætte med din ordre.",
    "First Name": "Fornavn",
    "Last Name": "Efternavn",
    "Email": "Email",
    "Phone": "Tlf",
    "School Name": "Skolenavn",
    "Address": "Adresse",
    "City": "By",
    "Postal Code": "Postnr",
    "Country": "Land",
    "Notes": "Besked",
    "Delivery Type": "Leveringstype",
    "Regular": "Almindelig",
    "Express": "Ekspres",
    "Deliver to School": "Levering til skole",
    "Order Reference": "Ordrenummer",
    "Total Paid": "Betalt i alt",
    "Items": "Produkter",
    "Balance Due": "Restbeløb",
    "Amount Paid": "Betalt beløb",
    "Place Order": "Afgiv ordre",
    "Confirm Order": "Bekræft ordre",
    "Continue": "Fortsæt",
    "Total Price": "Samlet pris",
    "Samlet pris": "Samlet pris",
    "400 DKK": "400 DKK",
    "Servicegebyr på 59,00 kr. inkl.": "Servicegebyr på 59,00 kr. inkl.",
    "Service fee of 59.00 kr. included": "Servicegebyr på 59,00 kr. inkluderet",

    // ── SUCCESS SCREEN ──
    "Thank You for Your Order!": "Tak for din bestilling",
    "Your payment was successful. We've sent a confirmation email to": "Din betaling blev gennemført. Vi har sendt en ordrebekræftelse til",
    "Continue Shopping": "Fortsæt med at handle",

    // ── CANCEL SCREEN ──
    "Payment Cancelled": "Betaling annulleret",
    "Your payment was not completed. If this was a mistake, you can try again or continue browsing our shop.": "Din betaling blev ikke gennemført. Hvis dette skete ved en fejl, kan du prøve igen eller fortsætte med at udforske vores webshop.",
    "Back to Shop": "Tilbage til shoppen",
    "Try Again": "Prøv igen",

    // ── LOGIN ──
    "Login": "Login",
    "Sign in to manage your dashboard": "Log ind for at administrere dit dashboard",
    "Log in": "Log ind for at administrere dit dashboard",
    "Forgot password?": "Glemt Adgangskode",
    "Forgot Password": "Glemt adgangskode",
    "Enter your email — a 6-digit OTP will be sent.": "Indtast din e-mailadresse – så sender vi en 6-cifret engangskode til dig.",
    "Send OTP": "Send engangskode",
    "Back to login": "Tilbage til login",
    "Already have OTP? Enter OTP": "Har du allerede en engangskode? Indtast den her",
    "Reset Password": "Nulstil adgangskode",
    "Enter the 6-digit OTP from your email and set a new password.": "Indtast den 6-cifrede engangskode fra din e-mail, og vælg en ny adgangskode.",
    "Resend OTP": "Send engangskode igen",
    "© 2024 ClothConfig. All rights reserved.": "© 2024 ClothConfig. Alle rettigheder forbeholdes.",

    // ── REGISTER ──
    "Student Registration": "Elevregistrering",
    "No registration token": "Ingen registreringskode",
    "Invalid registration link": "Ugyldigt registreringslink",
    "Get a registration link from your class representative to join your class.": "Få et registreringslink fra din klasserepræsentant for at tilmelde dig din klasse.",
    "This link is invalid or expired. Ask your class rep for a new link, or enter your class code below.": "Dette link er ugyldigt eller udløbet. Bed din klasserepræsentant om et nyt link, eller indtast din klassekode nedenfor.",
    "Enter Class Code Manually": "Indtast klassekode manuelt",
    "Go to Login": "Gå til login",
    "Loading...": "Indlæser...",
    "Join Your Class": "Tilmeld dig din klasse",
    "Register as a student for your class": "Opret dig som elev i din klasse",
    "Enter your class code to register": "Indtast din klassekode for at registrere dig",
    "I agree to receive marketing emails from StudentLife (optional)": "Ja tak, send mig eksklusive rabatter, nyheder og inspiration fra Student Life.",
    "Register": "Opret bruger",
    "Already have an account? Log in": "Har du allerede en konto? Log ind",
    "Forgot password? Reset it": "Glemt adgangskoden? Nulstil den",
    "Update Password": "Opdater adgangskode",

    // ── ADD STUDENTS POPUP ──
    "Add Students": "Tilføj elever",
    "Individual": "Enkeltvis",
    "Batch (Multiple)": "Flere ad gangen",
    "Student Name": "Elevens navn",
    "Enter full name": "Indtast fulde navn",
    "Student Names (max 10)": "Elevnavne (maks. 10)",
    "+ Add another student": "Tilføj endnu en elev",
    "Student 1": "Elev 1",
    "Student 2": "Elev 2",
    "Student 3": "Elev 3",
    "Student 4": "Elev 4",
    "Student 5": "Elev 5",
    "Student 6": "Elev 6",
    "Student 7": "Elev 7",
    "Student 8": "Elev 8",
    "Student 9": "Elev 9",
    "Student 10": "Elev 10",
    "Please enter student name": "Indtast elevens navn",
    "Please enter at least one student name": "Indtast mindst ét elevnavn",
    "Saved successfully!": "Gemt!",

    // ── INQUIRY MODAL ──
    "Fulde navn": "Fulde navn",
    "Indtast dit fulde navn": "Indtast dit fulde navn",
    "E-mailadresse": "E-mailadresse",
    "Telefonnummer": "Telefonnummer",
    "Forespørgsel som": "Jeg henvender mig som",
    "Klasserepræsentant": "Klasserepræsentant",
    "School Name (inquiry)": "Skole",
    "Enter school name": "Indtast skolens navn",
    "Class (optional)": "Klasse (valgfri)",
    "Enter class name": "Indtast klassens navn",
    "Besked": "Besked",
    "Beskriv din forespørgsel eller dine ønsker...": "Beskriv din forespørgsel eller dine ønsker...",
    "Annuller": "Annuller",
    "Send forespørgsel": "Send forespørgsel",
    "Forespørgsel sendt!": "Forespørgsel sendt!",
    "Tak fordi du kontaktede os. Vi har modtaget din forespørgsel og vil kontakte dig på": "Tak for din henvendelse. Vi har modtaget din forespørgsel og kontakter dig på",
    "snarest.": "hurtigst muligt.",
    "Luk": "Luk",
    "Navn er påkrævet": "Navn er påkrævet",
    "E-mail er påkrævet": "E-mailadresse er påkrævet",
    "Ugyldig e-mailadresse": "Ugyldig e-mailadresse",
    "Telefonnummer er påkrævet": "Telefonnummer er påkrævet",
    "School is required": "Skole er påkrævet",
    "Besked er påkrævet": "Besked er påkrævet",

    // ── UPLOAD REQUEST MODAL ──
    "Du skal først sende en anmodning, hvis du ønsker at uploade et design. Så snart din anmodning er godkendt, har du mulighed for at bruge dit eget design.": "Opret din klasse for at kunne uploade dit eget design.",
    "Opret klasse": "Opret klasse",
    "Your class needs to be signed up before you can add your own design.": "Din klasse skal være oprettet, før du kan tilføje dit eget design.",
    "To upload your own design, you need to send a request first. Once your request is approved, you will be able to upload your design.": "For at uploade dit eget design skal du først sende en forespørgsel. Når den er godkendt, kan du uploade dit design.",

    // ── BACK DESIGN POPUP ──
    "Back Design": "Rygdesign",
    "Applied to all students across all garments": "Anvendes på alle elever og alt tøj",
    "Browse Library": "Designbibliotek",
    "Upload / Edit": "Upload / Rediger",
    "White — Black print": "Hvid — Sort tryk",
    "Black — White print": "Sort — Hvidt tryk",
    "No [color] designs for this country": "Ingen [color] designs til dette land",
    "selected": "valgt",

    // ── DASHBOARD ──
    "StudentLife": "Student Life",
    "Cloth Configurator": "Tøjkonfigurator",
    "Profile": "Profil",
    "Info": "Oplysninger",
    "Edit": "Rediger",
    "Change Password": "Skift adgangskode",
    "Name": "Navn",
    "Class": "Klasse",
    "School": "Skole",
    "Save Changes": "Gem ændringer",
    "Current Password": "Nuværende adgangskode",
    "New Password": "Ny adgangskode",
    "Confirm Password": "Bekræft adgangskode",
    "Log Out": "Log ud",
    "Settings": "Indstillinger",
    "Unpaid": "Ikke betalt",
    "Paid": "Betalt",
    "Partially Paid": "Delvist betalt",
    "Locked": "Låst",
    "Unlocked": "Åben",
    "Deadline": "Deadline",
    "Back design: Pending / Approved / Rejected": "Rygdesign: Afventer / Godkendt / Afvist",

    // ── HISTORY MODAL ──
    "Order History": "Ordrehistorik",
    "Version": "Version",
    "Restore this version": "Gendan denne version",

    // ── COPY DESIGN ──
    "Copy Design?": "Kopiér design?",
    "Haan, Copy Karo": "Ja, kopiér",
    "Nahi, Alag Rakho": "Nej, behold separat",
    "Yes, Copy": "Ja, kopiér",
    "No, Keep Separate": "Nej, behold separat",

    // ── RESET ORDER MODAL ──
    "Are you sure you want to reset your order?": "Er du sikker på, at du vil nulstille din ordre?",
    "This will clear all your current designs.": "Dette vil slette alle dine nuværende designs.",
    "Create Fresh Order": "Opret ny ordre",

    // ── MISC ──
    "Currently Editing:": "Redigerer nu:",
    "Back Design:": "Rygdesign:",
    "Global Back Design": "Fælles rygdesign",
    "Design uploaded here will be applied to ALL students.": "Designs uploadet her vil blive anvendt på ALLE elever.",
    "Design Back": "Design ryg",
    "Pressure Options": "Trykmuligheder",
    "Individual Configuration": "Individuel tilpasning",
    "Students": "Elever",
    "Select a country above": "Vælg et land ovenfor",
    "Short": "Shorts",
};
